name: CI
on:
  push:
    branches: master
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build Docker Image
      run: |
        go run main.go build -u${{ secrets.ALIYUN_U }} -p${{ secrets.ALIYUN_P }}
        go run main.go build -u${{ secrets._GITHUB_U }} -p${{ secrets._GITHUB_P }} -r ghcr.io -o goudai-projects

